-- Auto-generated from schema-map-postgres.yaml (map@4ae85c5)
-- engine: postgres
-- table:  inventory_reservations

CREATE TABLE IF NOT EXISTS inventory_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  book_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  reserved_until TIMESTAMPTZ(6) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_reservations_version CHECK (version >= 0),
  CONSTRAINT chk_res_qty CHECK (quantity > 0),
  CONSTRAINT chk_res_status CHECK (status IN ('pending','confirmed','expired','cancelled')),
  CONSTRAINT chk_res_until_after_created CHECK (reserved_until > created_at)
);
